name: Deploy React App to GitHub Pages
on:
  push:
    branches:
<<<<<<< HEAD
      - main
=======
      - main  # your default branch

>>>>>>> 878aa8a6af344fee6115624503902cf2d4889572
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
<<<<<<< HEAD
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
=======
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./client/dist
>>>>>>> 878aa8a6af344fee6115624503902cf2d4889572
